VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "ONSEncript"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Private Function GeneralKey() As String()
        Dim StrGeneralKey(100) As String
        StrGeneralKey(0) = "MUOSFDW"
        StrGeneralKey(1) = "GSUNHTR"
        StrGeneralKey(2) = "XS0CHOP"
        StrGeneralKey(3) = "DPRWIF2"
        StrGeneralKey(4) = "YOE9YB5"
        StrGeneralKey(5) = "SDMAR57"
        StrGeneralKey(6) = "436V9FV"
        StrGeneralKey(7) = "TE57JM6"
        StrGeneralKey(8) = "HPEMFUF"
        StrGeneralKey(9) = "RNJGPYE"
        StrGeneralKey(10) = "5J8YWQA"
        StrGeneralKey(11) = "QEAPFV5"
        StrGeneralKey(12) = "JTZ3S6N"
        StrGeneralKey(13) = "MR5V0JK"
        StrGeneralKey(14) = "YRUU45X"
        StrGeneralKey(15) = "TV7KXTY"
        StrGeneralKey(16) = "RUSIQ3G"
        StrGeneralKey(17) = "HPEMFUF"
        StrGeneralKey(18) = "RNJGPYE"
        StrGeneralKey(19) = "5J8YWQA"
        StrGeneralKey(20) = "QEAPFV5"
        StrGeneralKey(21) = "JTZ3S6N"
        StrGeneralKey(22) = "MR5V0JK"
        StrGeneralKey(23) = "YRUU45X"
        StrGeneralKey(24) = "TV7KXTY"
        StrGeneralKey(25) = "RUSIQ3G"
        StrGeneralKey(26) = "HPEMFUF"
        StrGeneralKey(27) = "RNJGPYE"
        StrGeneralKey(28) = "5J8YWQA"
        StrGeneralKey(29) = "QEAPFV5"
        StrGeneralKey(30) = "JTZ3S6N"
        StrGeneralKey(31) = "MR5V0JK"
        StrGeneralKey(32) = "YRUU45X"
        StrGeneralKey(33) = "TV7KXTY"
        StrGeneralKey(34) = "RUSIQ3G"
        StrGeneralKey(35) = "HPEMFUF"
        StrGeneralKey(36) = "RNJGPYE"
        StrGeneralKey(37) = "5J8YWQA"
        StrGeneralKey(38) = "QEAPFV5"
        StrGeneralKey(39) = "JTZ3S6N"
        StrGeneralKey(40) = "MR5V0JK"
        StrGeneralKey(41) = "YRUU45X"
        StrGeneralKey(42) = "TV7KXTY"
        StrGeneralKey(43) = "RUSIQ3G"
        StrGeneralKey(44) = "HPEMFUF"
        StrGeneralKey(45) = "RNJGPYE"
        StrGeneralKey(46) = "5J8YWQA"
        StrGeneralKey(47) = "QEAPFV5"
        StrGeneralKey(48) = "JTZ3S6N"
        StrGeneralKey(49) = "MR5V0JK"
        StrGeneralKey(50) = "YRUU45X"
        StrGeneralKey(51) = "TV7KXTY"
        StrGeneralKey(52) = "RUSIQ3G"
        StrGeneralKey(53) = "HPEMFUF"
        StrGeneralKey(54) = "RNJGPYE"
        StrGeneralKey(55) = "5J8YWQA"
        StrGeneralKey(56) = "QEAPFV5"
        StrGeneralKey(57) = "JTZ3S6N"
        StrGeneralKey(58) = "MR5V0JK"
        StrGeneralKey(59) = "YRUU45X"
        StrGeneralKey(60) = "TV7KXTY"
        StrGeneralKey(61) = "RUSIQ3G"
        StrGeneralKey(62) = "HPEMFUF"
        StrGeneralKey(63) = "RNJGPYE"
        StrGeneralKey(64) = "5J8YWQA"
        StrGeneralKey(65) = "QEAPFV5"
        StrGeneralKey(66) = "JTZ3S6N"
        StrGeneralKey(67) = "MR5V0JK"
        StrGeneralKey(68) = "YRUU45X"
        StrGeneralKey(69) = "TV7KXTY"
        StrGeneralKey(70) = "RUSIQ3G"
        StrGeneralKey(71) = "HPEMFUF"
        StrGeneralKey(72) = "RNJGPYE"
        StrGeneralKey(73) = "5J8YWQA"
        StrGeneralKey(74) = "QEAPFV5"
        StrGeneralKey(75) = "JTZ3S6N"
        StrGeneralKey(76) = "MR5V0JK"
        StrGeneralKey(77) = "YRUU45X"
        StrGeneralKey(78) = "TV7KXTY"
        StrGeneralKey(79) = "RUSIQ3G"
        StrGeneralKey(80) = "HPEMFUF"
        StrGeneralKey(81) = "RNJGPYE"
        StrGeneralKey(82) = "5J8YWQA"
        StrGeneralKey(83) = "QEAPFV5"
        StrGeneralKey(84) = "JTZ3S6N"
        StrGeneralKey(85) = "MR5V0JK"
        StrGeneralKey(86) = "YRUU45X"
        StrGeneralKey(87) = "TV7KXTY"
        StrGeneralKey(88) = "RUSIQ3G"
        StrGeneralKey(89) = "WMYHAK9"
        StrGeneralKey(90) = "3NLLIGN"
        StrGeneralKey(91) = "MPK5MAA"
        StrGeneralKey(92) = "VKZCHU2"
        StrGeneralKey(93) = "Z8LU2W1"
        StrGeneralKey(94) = "PZFV20P"
        StrGeneralKey(95) = "OHZOP8V"
        StrGeneralKey(96) = "ZSECQTO"
        StrGeneralKey(97) = "2RJ8JIU"
        StrGeneralKey(98) = "N47KOLC"
        StrGeneralKey(99) = "CMBG2RI"
        StrGeneralKey(100) = "DCJNR9Z"
        GeneralKey = StrGeneralKey()
End Function

Public Function RandString(strLen As Integer) As String
       On Error Resume Next
       Dim xChar As Integer
       Randomize
       While strLen <> 0
             xChar = Rnd * 255
             If IsAlphaNumeric(xChar) = True Then
                RandString = RandString & Chr(xChar)
                strLen = strLen - 1
             End If
       Wend
End Function

Private Function IsAlphaNumeric(CharCode As Integer) As Boolean
        On Error Resume Next
        If (CharCode >= 65 And CharCode <= 90) Then
           IsAlphaNumeric = True
        ElseIf (CharCode >= 97 And CharCode <= 122) Then
           IsAlphaNumeric = True
        ElseIf (CharCode >= 48 And CharCode <= 57) Then
           IsAlphaNumeric = True
        Else
           IsAlphaNumeric = False
        End If
End Function

Public Function EncryptText(strText As String, ByVal strPwd As String) As String
       Dim i As Integer, c As Integer
       Dim strBuff As String
       If Len(strPwd) Then
          For i = 1 To Len(strText)
              c = Asc(Mid$(strText, i, 1))
              c = c + Asc(Mid$(strPwd, (i Mod Len(strPwd)) + 1, 1))
              strBuff = strBuff & Chr$(c And &HFF)
          Next i
       Else
          strBuff = strText
       End If
       EncryptText = strBuff
End Function

Public Function DecryptText(strText As String, ByVal strPwd As String) As String
       Dim i As Integer, c As Integer
       Dim strBuff As String
       If Len(strPwd) Then
          For i = 1 To Len(strText)
              c = Asc(Mid$(strText, i, 1))
              c = c - Asc(Mid$(strPwd, (i Mod Len(strPwd)) + 1, 1))
              strBuff = strBuff & Chr$(c And &HFF)
          Next i
       Else
          strBuff = strText
       End If
       DecryptText = strBuff
       Exit Function
End Function

Public Function ONSEncriptPassword(Password As String) As String
       On Error Resume Next
       Dim TEMP
       Dim i As Integer
       Dim ENCPassword As String
       
       ONSEncriptPassword = ""
       i = 100 * Rnd: If i = 0 Then i = 1
       TEMP = GeneralKey()
      
       ENCPassword = "": ENCPassword = EncryptText(Password, CStr(TEMP(i - 1)))
       ONSEncriptPassword = ENCPassword & EncryptText(CStr(Format(i, "000")), "ONS")
End Function

Public Function ONSDecriptPassword(Password As String) As String
       On Error Resume Next
       Dim TEMP
       Dim i As Integer
       Dim ENCPassword As String
       ONSDecriptPassword = ""
       
       i = Val(DecryptText(Right(Password, 3), "ONS"))
       TEMP = GeneralKey()
      
       ENCPassword = "": ENCPassword = DecryptText(Left(Password, (Len(Password) - 3)), CStr(TEMP(i - 1)))
       ONSDecriptPassword = ENCPassword
End Function

